# Generated by Django 4.1.7 on 2023-05-02 14:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kataru_api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='genre',
            name='level',
            field=models.CharField(default='', max_length=30),
            preserve_default=False,
        ),
    ]
