# Generated by Django 4.1.7 on 2023-05-02 16:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('kataru_api', '0003_user'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='user',
            table='user_',
        ),
    ]
