# Generated by Django 4.1.7 on 2023-05-07 12:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('kataru_api', '0004_alter_user_table'),
    ]

    operations = [
        migrations.RenameField(
            model_name='genre',
            old_name='modified_at',
            new_name='updated_at',
        ),
        migrations.RenameField(
            model_name='prompt',
            old_name='modified_at',
            new_name='updated_at',
        ),
        migrations.RenameField(
            model_name='user',
            old_name='modified_at',
            new_name='updated_at',
        ),
    ]
