# Generated by Django 4.1.7 on 2023-05-09 07:41

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('kataru_api', '0005_rename_modified_at_genre_updated_at_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Story',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('title', models.CharField(max_length=100)),
                ('genre', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='kataru_api.genre')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='kataru_api.user')),
            ],
            options={
                'db_table': 'story',
            },
        ),
        migrations.CreateModel(
            name='Prompt_Registry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('prompt', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='kataru_api.prompt')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='kataru_api.user')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Entry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('entry_text', models.TextField()),
                ('genre', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='kataru_api.genre')),
                ('prompt', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='kataru_api.prompt')),
                ('story', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='kataru_api.story')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='kataru_api.user')),
            ],
            options={
                'db_table': 'entry',
            },
        ),
    ]
