# Generated by Django 4.1.7 on 2023-05-09 07:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('kataru_api', '0006_story_prompt_registry_entry'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='prompt_registry',
            table='prompt_registry',
        ),
    ]
