# Generated by Django 4.1.7 on 2023-05-12 04:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('kataru_api', '0007_alter_prompt_registry_table'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Prompt_Registry',
            new_name='PromptRegistry',
        ),
    ]
